### ISSUE TITLE
Issue with numbers in geological timescale vocabulary.

### ISSUE THREAD

**Issue by JakeJones161096** [CSIRO-enviro-informatics/interactive-geological-timescale#10]
Hi,
Just noticed that there are (what looks like) two errors in the numerical data on the Geological Timescale. I have details of the errors, and the corrections I propose (based on the [ICS Chart v2018-08](http://www.stratigraphy.org/ICSchart/ChronostratChart2018-08.pdf)) in the attached file below.

Cheers!

[Errors in Geological Timescale.txt](https://github.com/CSIRO-enviro-informatics/interactive-geological-timescale/files/3357264/Errors.in.Geological.Timescale.txt)

**Comment by JakeJones161096** [comment]
For the moment, I have manually modified the JSON that we normally get from a query to the SPARQL endpoint to reflect those corrections

**Comment by dr-shorthair** [comment]
Thanks @JakeJones161096 
I believe I have now fixed it in RVA (and also in GitHub - https://github.com/GeoscienceAustralia/geosciml.org/tree/master/resource/static/vocabulary/timescale )

**Comment by JakeJones161096** [comment]
Yep, that did it!
