### ISSUE TITLE
Another Vocabulary issue

### ISSUE THREAD

**Issue by JakeJones161096** [CSIRO-enviro-informatics/interactive-geological-timescale#11]
Hi @dr-shorthair 

I came across another minor problem in the [Geological Time Vocabulary](https://vocabs.ands.org.au/viewById/196) again, basically you just need to add a few triples where they are missing.

All parents of the Holocene epoch need to be given narrowerTransitive relationships with its children. Again, I have details in the attached text file.

Cheers!

[More Errors in Geological Timescale.txt](https://github.com/CSIRO-enviro-informatics/interactive-geological-timescale/files/3361049/More.Errors.in.Geological.Timescale.txt)

**Comment by dr-shorthair** [comment]
Formatted like this: 
```
skos:narrowerTransitive <http://resource.geosciml.org/classifier/ics/ischart/Greenlandian> ;
skos:narrowerTransitive <http://resource.geosciml.org/classifier/ics/ischart/Meghalayan> ;
skos:narrowerTransitive <http://resource.geosciml.org/classifier/ics/ischart/Northgrippian> ;
```
They can be dropped straight into the Turtle file in three places! 

You could make a fork and then issue a PR. 
Better way to collaborate and also better record keeping.

**Comment by JakeJones161096** [comment]
I had a look, I see what you mean! If I come across any more issues, I will do this instead.

Cheers!

**Comment by dr-shorthair** [comment]
Strictly the narrowTransitive axioms don't need to be present, as they can be inferred because of (a) the inverse relationships (b) the chain of narrower relationships. But for consistency and completeness they should be added.
