### ISSUE TITLE
Add URL of deployed application to README.md 

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/interactive-geological-timescale#20]
I can't currently see a link to the actual application

**Comment by JakeJones161096** [comment]
Good call @dr-shorthair . At the moment, I'm not sure where (if) it is deployed. I will look into it and find out and add the link when I do!

**Comment by nicholascar** [comment]
Have added this to README with Commit https://github.com/CSIRO-enviro-informatics/interactive-geological-timescale/commit/077f1b1adc2835a722ce28752bb49169878ec6cd
