### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/interactive-geological-timescale#3]
Footer needs to have [CSIRO logo](https://www.csiro.au/~/media/Web-team/Images/CSIRO_Logo/CSIRO_Logo.svg), [GSQ logo](https://avatars0.githubusercontent.com/u/46978240) and not Copyright &copy; 2019 Jake Hashim-Jones!

Using your own styling, put in this footer content:

"This visualisation of the [International Commission on Stratigraphy](http://www.stratigraphy.org)'s [Chronostratigraphic Chart](http://www.stratigraphy.org/index.php/ics-chart-timescale) uses the [SKOS](https://www.w3.org/TR/skos-primer/) &amp; [Time Ontology in OWL](https://www.w3.org/TR/owl-time/) representation of it as the [Geological Timescale (2018)](http://resource.geosciml.org/vocabulary/timescale/gts2018) for its data."

and 

"The work to develop this was supported by [CSIRO](https://www.csiro.au/)'s [Environmental Informatics Group](https://research.csiro.au/ei/) and the [Geological survey of Queensland](https://www.business.qld.gov.au/industries/mining-energy-water/resources/geoscience-information/gsq)."

At least get those sentences in an some presentation of the logos with links back to CSIRO & GSQ. You might then add:

"This tool was developed by [Jake Hashim-Jones](https://github.com/JakeJones161096)"

or whatever other attribution for you you like.

**Comment by JakeJones161096** [comment]
Done. To be included in the next commit.
