### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/interactive-geological-timescale#4]
Keep it simple - the colours of the chart are enough fancy!

* add "Interactive" in small font above "INTERNATIONAL CHRONOSTRATIGRAPHIC CHART"
* add "An interactive version of the [International Chronostratigraphic Chart](http://www.stratigraphy.org/index.php/ics-chart-timescale), based on it's [Semantic Web](https://www.w3.org/standards/semanticweb/) representation" below "INTERNATIONAL CHRONOSTRATIGRAPHIC CHART" in a mini explanatory paragraph.
  * also add "For comments/issues and this visualisation's code, please see its [Git Code Repository](https://github.com/CSIRO-enviro-informatics/interactive-geological-timescale)"

**Comment by JakeJones161096** [comment]
Done. To be included in the next commit.
