### ISSUE TITLE
Make links in pop-ups actionable

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/interactive-geological-timescale#7]
The pop-ups show a useful selection of the information from the graph, but do not allow you to burrow-through to some key data, in particular, the Beginning and End details which is where the numeric values and the information about the GSSPs is found.

**Comment by JakeJones161096** [comment]
Still have not included the numerical values yet, however we do know where they are. We can now burrow a little deeper on the Beginning and End details and find information about the GSSPs (if available)!

**Comment by JakeJones161096** [comment]
Done!
